% Function to evaluate the magnetic field B at a point generated by a
% circular coil located at c_coil, with a radius R_coil. The coil will be
% approximated by a cylinder with a distributed current density. The coil is oriented
% according to c_axis with a global coordinate system typical in tokamaks:
% X (radial), Y (toroidal) Z (vertical)

% r=[.3 .3 0]';
% R_coil=.35;
% r_plasma=.4;
% I=1e3;

function [output]=magn_field_distrib_plasma_toroid_3D(I,r,c_coil,R_coil,r_plasma)
global mu0 

r_local_coords= r-[R_coil 0 0]'; % Local coords of grid point (relative to plasma center)


if  norm(r_local_coords) <= r_plasma; %into plasma
    B_mod=mu0*I*norm(r_local_coords)^2/2/pi/r_plasma^3;
else  %out plasma
    B_mod=mu0*I/2/pi/norm(r_local_coords);
end

r_perp=[-r_local_coords(3) 0 r_local_coords(1)]';
B_unit=r_perp/norm(r_perp);
output.B=B_mod*B_unit;
output.mod_B=B_mod;

